/* autogenerated by embedmodel.py.  DO NOT EDIT */

#include "northbound.h"

static const char model[] =
	"module frr-deviations-ietf-key-chain {\n"
	"  yang-version 1.1;\n"
	"  namespace \"http://frrouting.org/yang/frr-deviations-ietf-key-chain\";\n"
	"  prefix frr-deviations-ietf-key-chain;\n"
	"\n"
	"  import ietf-key-chain {\n"
	"    prefix kc;\n"
	"  }\n"
	"\n"
	"  organization\n"
	"    \"FRRouting\";\n"
	"  contact\n"
	"    \"FRR Users List:       <mailto:frog@lists.frrouting.org>\n"
	"     FRR Development List: <mailto:dev@lists.frrouting.org>\";\n"
	"  description\n"
	"    \"This module defines deviation statements for the ietf-key-chain\n"
	"     module.\";\n"
	"\n"
	"  revision 2024-03-03 {\n"
	"    description \"Initial revision.\";\n"
	"    reference \"RFC 8177: YANG Data Model for Key Chains\";\n"
	"  }\n"
	"\n"
	"  deviation /kc:key-chains/kc:key-chain/kc:key/kc:crypto-algorithm {\n"
	"    deviate replace {\n"
	"      mandatory false;\n"
	"    }\n"
	"  }\n"
	"}\n"
	"";

static struct yang_module_embed embed = {
	.mod_name = "frr-deviations-ietf-key-chain",
	.mod_rev = "2024-03-03",
	.sub_mod_name = "",
	.sub_mod_rev = "",
	.data = model,
	.format = LYS_IN_YANG,
};

static void embed_register(void) __attribute__((_CONSTRUCTOR(2000)));
static void embed_register(void)
{
	yang_module_embed(&embed);
}
