/* autogenerated by embedmodel.py.  DO NOT EDIT */

#include "northbound.h"

static const char model[] =
	"module frr-ospf-route-map {\n"
	"  yang-version 1.1;\n"
	"  namespace \"http://frrouting.org/yang/ospf-route-map\";\n"
	"  prefix frr-ospf-route-map;\n"
	"\n"
	"  import ietf-inet-types {\n"
	"    prefix inet;\n"
	"  }\n"
	"\n"
	"  import frr-route-map {\n"
	"    prefix frr-route-map;\n"
	"  }\n"
	"\n"
	"  organization\n"
	"    \"Free Range Routing\";\n"
	"  contact\n"
	"    \"FRR Users List:       <mailto:frog@lists.frrouting.org>\n"
	"     FRR Development List: <mailto:dev@lists.frrouting.org>\";\n"
	"  description\n"
	"    \"This module defines ospf route map settings\";\n"
	"\n"
	"  revision 2020-01-02 {\n"
	"    description\n"
	"      \"Initial revision\";\n"
	"  }\n"
	"\n"
	"  identity metric-type {\n"
	"    base frr-route-map:rmap-set-type;\n"
	"    description\n"
	"      \"Set the type of metric\";\n"
	"  }\n"
	"\n"
	"  augment \"/frr-route-map:lib/frr-route-map:route-map/frr-route-map:entry/frr-route-map:set-action/frr-route-map:rmap-set-action/frr-route-map:set-action\" {\n"
	"    case metric-type {\n"
	"      when \"derived-from-or-self(../frr-route-map:action, \'metric-type\')\";\n"
	"      leaf metric-type {\n"
	"        type enumeration {\n"
	"          enum \"type-1\" {\n"
	"            value 0;\n"
	"            description\n"
	"              \"OSPF6 external type 1 metric\";\n"
	"          }\n"
	"          enum \"type-2\" {\n"
	"            value 1;\n"
	"            description\n"
	"              \"OSPF6 external type 2 metric\";\n"
	"          }\n"
	"        }\n"
	"      }\n"
	"    }\n"
	"  }\n"
	"}\n"
	"";

static struct yang_module_embed embed = {
	.mod_name = "frr-ospf-route-map",
	.mod_rev = "2020-01-02",
	.sub_mod_name = "",
	.sub_mod_rev = "",
	.data = model,
	.format = LYS_IN_YANG,
};

static void embed_register(void) __attribute__((_CONSTRUCTOR(2000)));
static void embed_register(void)
{
	yang_module_embed(&embed);
}
